name: 'Testing'
on:
  push:

jobs:
  UnitTest:
    name: 'Unit Test'
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
